$ErrorActionPreference='Stop';$repo=Split-Path $PSScriptRoot -Parent
. (Join-Path $repo 'scripts/lib/msg_norm.ps1');. (Join-Path $repo 'scripts/lib/reply_policy.ps1');. (Join-Path $repo 'scripts/lib/human_pause.ps1')
$root=Join-Path $env:TEMP ('aar-closure-edges-'+[guid]::NewGuid().ToString('N'));[void](Initialize-AarIsolation $root)
$script:pass=0;$script:fail=0
function Assert($ok,$why='assertion failed'){if(-not $ok){throw $why}}
function Case($id,[scriptblock]$body){try{& $body;$script:pass++;Write-Output "PASS $id"}catch{$script:fail++;Write-Output "FAIL $id $($_.Exception.Message)"}}
function BL($text){'[BUYER] '+$text+' @@MT:1791172800000'}
Case D06-buyer-negative {foreach($bad in @('-5 cartons, total weight -12 kg, carton dimensions -50x40x30 cm, Amazon FTW1.','10 cartons, total weight 120 kg, carton dimensions 50x40x30, Amazon FTW1.')){$cf=Get-CargoFacts (ConvertTo-MessageList (BL $bad));Assert (-not(Get-QuoteReadiness $cf).Ready) 'negative/missing-unit buyer input cannot become valid positive cargo'};$cf=Get-CargoFacts (ConvertTo-MessageList (BL '10 cartons, total weight 120 kg, carton dimensions 50x40x30 cm, Amazon FTW1.'));Assert (Get-QuoteReadiness $cf).Ready}
Case P03-corresponding-source {$facts=Get-ConversationFacts (ConvertTo-MessageList (BL "Supplier contact is factory@example.invalid. Total weight 120 kg."));$d=[pscustomobject]@{Facts=$facts;AskFields=@();RequestedFacts=@()};Assert (Test-ReplyCompliance 'We have received the supplier contact details.' -Decision $d).Ok;Assert (-not(Test-ReplyCompliance 'We have received the recipient contact details.' -Decision $d).Ok);Assert (-not(Test-ReplyCompliance 'We have received the carton dimensions.' -Decision $d).Ok)}
Case H08-legacy-no-anchor {$now=[datetime]::SpecifyKind([datetime]'2026-10-05T04:00:00',[DateTimeKind]::Utc);[IO.File]::WriteAllText((Get-HumanPauseFile),'{"version":1,"pauses":{"legacy":{"reason":"human"}}}');$r=Sync-ConversationInterventionState -Buyer legacy -Lines @('[BUYER] old request') -NowUtc $now;Assert ($r.SyncOk -and $r.HumanPauseActive);$until=Get-HumanPauseUntilUtc (Get-HumanPause legacy);Assert ($until -eq $now.AddMinutes(5));$r=Sync-ConversationInterventionState -Buyer legacy -Lines @('[BUYER] old request') -NowUtc $now.AddMinutes(2);Assert ((Get-HumanPauseUntilUtc (Get-HumanPause legacy)) -eq $until) 'legacy adoption does not renew';$r=Sync-ConversationInterventionState -Buyer legacy -Lines @('[BUYER] old request') -NowUtc $now.AddMinutes(6);Assert (-not $r.HumanPauseActive)}
Case D10-concurrent {
    $a=New-OrUpdate-SupplierVerificationTask -Buyer 'Concurrent A' -TriggerMessage 'Need packing' -SupplierContact 'a@example.invalid' -MissingFields @('unit_weight')
    $b=New-OrUpdate-SupplierVerificationTask -Buyer 'Concurrent B' -TriggerMessage 'Need packing' -SupplierContact 'b@example.invalid' -MissingFields @('unit_weight')
    $worker=Join-Path $root 'concurrent.ps1'
    $body=@'
param($Repo,$Root,$TaskId,$Mode,$Nonce,$Proof)
$ErrorActionPreference='Stop';$env:AAR_TEST_LAYER='Offline';$env:AAR_TEST_NAME='concurrent-fixture';$env:AAR_TEST_NONCE=$Nonce;$env:AAR_ATTESTATION_FILE=$Proof
. (Join-Path $Repo 'scripts/lib/msg_norm.ps1');[void](Initialize-AarIsolation $Root)
[IO.File]::WriteAllText((Join-Path $Root ($Nonce+'.ready')),'ready');while(-not(Test-Path (Join-Path $Root 'go'))){Start-Sleep -Milliseconds 50}
for($i=0;$i -lt 20;$i++){if($Mode -eq 'notice'){if(-not(Add-HumanTaskNotification $TaskId -Delivered $false -Detail ('attempt '+$i))){throw 'notice failed'}}else{$r=Add-HumanTaskActionRecord -Id $TaskId -ActionKind supplier_reply -Source operator-entry -RecordedBy 'fixture operator' -SourceRef ('concurrent:'+ $i) -AtUtc '2026-10-05T04:01:00Z' -RawContent 'Supplier said 12 kg per carton' -ConfirmedFields @(@{FieldKey='unit_weight';Value='12';Unit='kg';Scope='unit'});if(-not $r.Ok){throw $r.Error}}}
Write-Output 'WORKER completed=20';exit 0
'@
    [IO.File]::WriteAllText($worker,$body,(New-Object Text.UTF8Encoding($true)))
    $children=@();foreach($pair in @(@($a.Task.id,'notice'),@($b.Task.id,'record'))){$nonce=[guid]::NewGuid().ToString('N');$proof=Join-Path $root ($nonce+'.proof.json');$psi=New-Object Diagnostics.ProcessStartInfo;$psi.FileName='powershell.exe';$psi.Arguments='-NoProfile -ExecutionPolicy Bypass -File "'+$worker+'" -Repo "'+$repo+'" -Root "'+$root+'" -TaskId "'+$pair[0]+'" -Mode '+$pair[1]+' -Nonce '+$nonce+' -Proof "'+$proof+'"';$psi.UseShellExecute=$false;$psi.CreateNoWindow=$true;$psi.RedirectStandardOutput=$true;$psi.RedirectStandardError=$true;$p=New-Object Diagnostics.Process;$p.StartInfo=$psi;[void]$p.Start();$children+=@{Process=$p;Nonce=$nonce;Proof=$proof;Stdout=$p.StandardOutput.ReadToEndAsync();Stderr=$p.StandardError.ReadToEndAsync()};$watch=[Diagnostics.Stopwatch]::StartNew();while(-not(Test-Path (Join-Path $root ($nonce+'.ready')))){if($watch.Elapsed.TotalSeconds -gt 10){throw 'worker initialization timeout'};Start-Sleep -Milliseconds 50}}
    [IO.File]::WriteAllText((Join-Path $root 'go'),'go')
    foreach($child in $children){$p=$child.Process;$p.WaitForExit();Assert ($p.ExitCode -eq 0) $child.Stderr.Result;$proof=Get-Content $child.Proof -Raw|ConvertFrom-Json;Assert (Test-AarChildAttestation $proof -ExpectedPID $p.Id -Nonce $child.Nonce -TestName concurrent-fixture).Ok;Write-Output ('CONCURRENT-CHILD pid='+$p.Id+' nonce='+$child.Nonce+' verified=True exit='+$p.ExitCode);$p.Dispose()}
    [void](Initialize-AarIsolation $root);$aa=@(Get-HumanTaskList -TaskId $a.Task.id)[0];$bb=@(Get-HumanTaskList -TaskId $b.Task.id)[0];Assert ($aa.notification.attempts -eq 20);Assert (@($bb.actionRecords).Count -eq 20) 'records survive competing task update'
    $write=(Get-Command Write-JsonDocumentAtomic).ScriptBlock;try{function Write-JsonDocumentAtomic {return [pscustomobject]@{Ok=$false;Error='injected write fault'}};$result=Add-HumanTaskActionRecord -Id $b.Task.id -ActionKind contacted -Source operator-entry -RecordedBy 'fixture operator' -SourceRef 'write-fault' -AtUtc '2026-10-05T04:01:00Z' -RawContent 'Operator called supplier';Assert (-not $result.Ok)}finally{Set-Item Function:Write-JsonDocumentAtomic $write};Assert (@(Get-HumanTaskList -TaskId $b.Task.id)[0].actionRecords.Count -eq 20) 'write failure does not publish record'
}
Write-Output "RESULT closure_edges pass=$script:pass fail=$script:fail root=$root";if($script:fail){exit 1}
