$ErrorActionPreference = 'Stop'
$repo = Split-Path $PSScriptRoot -Parent
. (Join-Path $repo 'scripts/config.ps1')
. (Join-Path $repo 'scripts/lib/paths.ps1')
$root = Join-Path $env:TEMP ('aar-closure-s1-' + [guid]::NewGuid().ToString('N'))
[void](Initialize-AarIsolation -Root $root)
. (Join-Path $repo 'scripts/reply_engine.ps1')
. (Join-Path $repo 'scripts/lib/msg_norm.ps1')
. (Join-Path $repo 'scripts/lib/human_tasks.ps1')
. (Join-Path $repo 'scripts/lib/task_facts.ps1')
. (Join-Path $repo 'scripts/lib/goods.ps1')
. (Join-Path $repo 'scripts/lib/quote.ps1')
$script:pass=0; $script:fail=0
function Assert($condition,$detail='assertion failed') { if (-not $condition) { throw $detail } }
function Case($id,[scriptblock]$body) { try { & $body; $script:pass++; Write-Output "PASS $id" } catch { $script:fail++; Write-Output "FAIL $id $($_.Exception.Message)" } }
function BL($text,$ts=1791172800000L) { '[BUYER] '+$text+' @@TS:'+$ts+' @@MT:'+$ts+' @@OT:'+([Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($text))) }
function ClearTaskFixture { foreach($p in @((Get-HumanTaskFile),((Get-HumanTaskFile)+'.bak'))) { if(Test-Path $p){Remove-Item -LiteralPath $p -Force} } }
function Task($contact='one@example.invalid',$trig='Please verify this packing data.') { New-OrUpdate-SupplierVerificationTask -Buyer 'Closure Buyer' -SupplierContact $contact -TriggerMessage $trig -TriggerAt '2026-10-05T04:00:00Z' -MissingFields @('carton_count','unit_weight','unit_dimensions','delivery_address') }
function Record($id,$fields,$correction=$null) { $args=@{Id=$id;ActionKind='supplier_reply';Source='operator-entry';RecordedBy='isolated-operator';SourceRef='call:fixture-1';AtUtc='2026-10-05T04:01:00Z';RawContent='Supplier actually gave these packing values.';ConfirmedFields=$fields}; if($correction){$args.CorrectionOfFactRef=$correction}; Add-HumanTaskActionRecord @args }
$good=@(@{FieldKey='carton_count';Value='10';Unit='cartons';Scope='cartons'},@{FieldKey='unit_weight';Value='12';Unit='kg';Scope='unit'},@{FieldKey='unit_dimensions';Value='50x40x30';Unit='cm';Scope='unit'},@{FieldKey='delivery_address';Value='Amazon FTW1';Unit='';Scope='destination'})
Case D01 { ClearTaskFixture; $t=Task; Assert $t.StoreOk; Assert (Record $t.Task.id $good).Ok; . (Join-Path $repo 'scripts/lib/human_tasks.ps1'); $txt=BL 'Can you quote this shipment?' 1791172920000L; $r=Get-QuoteReadinessForConversationText -Text $txt -ConvoName 'Closure Buyer' -WithTaskEvidence; Assert $r.Ready 'persisted current flow must survive truncated window'; Assert (@(Get-TaskConfirmedEvidence -Buyer 'Closure Buyer' -Conversation (ConvertTo-MessageList $txt 'Closure Buyer')).Count -eq 4) }
Case D02 { ClearTaskFixture; $t=Task; Assert (Record $t.Task.id $good).Ok; foreach($msg in @('This is a new shipment, from another supplier two@example.invalid.','This is a new batch, same supplier one@example.invalid.')){ $txt=(BL '10 cartons; total weight: 120 kg; carton dimensions 50x40x30 cm; Amazon FTW1.')+"`n"+(BL $msg 1791172920000L); $r=Get-QuoteReadinessForConversationText -Text $txt -ConvoName 'Closure Buyer' -WithTaskEvidence; Assert (-not $r.Ready) 'old messages and task fields cannot enter new flow' } }
Case D02-phone-flow {ClearTaskFixture;$t=Task '+15551234001';Assert (Record $t.Task.id $good).Ok;$same=Get-QuoteReadinessForConversationText -Text (BL 'Can you quote?' 1791172860000L) -ConvoName 'Closure Buyer' -WithTaskEvidence;Assert $same.Ready 'same supplier phone flow survives truncation';$r=Get-QuoteReadinessForConversationText -Text (BL 'The supplier phone is now +15551234002. Can you quote?' 1791172920000L) -ConvoName 'Closure Buyer' -WithTaskEvidence;Assert (-not $r.Ready) 'changed phone identity cannot reuse previous confirmations';Assert ((Get-CurrentCargoFlow 'Closure Buyer').Id -ne $t.Task.FlowId)}
Case D03 { ClearTaskFixture; $t=Task; $all=@(Get-HumanTaskList); Set-HumanTaskField $all[0] FlowId ''; [void](Save-HumanTaskStore $all); $conv=ConvertTo-MessageList (BL 'Please verify this packing data.') 'Closure Buyer'; $s=Select-RelatedHumanTask -Buyer 'Closure Buyer' -Conversation $conv; Assert (-not $s.Selected -and $s.Ambiguous) 'one task / old trigger alone is not association' }
Case D04 { ClearTaskFixture; $a=Task ''; $b=Task 'one@example.invalid'; Assert ($a.Task.id -eq $b.Task.id) 'awaiting contact keeps task'; Assert ($a.Task.FlowId -eq $b.Task.FlowId -and $b.Task.FlowId) 'flow preserved'; Assert ((Get-ActionEvidenceForTask -Buyer 'Closure Buyer' -TaskId $b.Task.id -Kind supplier_verification -SupplierIdentity 'email:one@example.invalid').HasUsableSupplierContact) }
Case D04-truncated-contact {ClearTaskFixture;$first=Task;$again=New-OrUpdate-SupplierVerificationTask -Buyer 'Closure Buyer' -TriggerMessage 'Please keep checking the packing.' -MissingFields @('unit_weight');Assert ($again.Task.id -eq $first.Task.id -and $again.Task.FlowId -eq $first.Task.FlowId);Assert ($again.Task.supplierContact -eq 'one@example.invalid');Assert (Get-ActionEvidenceForTask -Buyer 'Closure Buyer' -TaskId $first.Task.id).HasUsableSupplierContact}
Case D05 { foreach($key in @('unit_weight','total_weight')){ClearTaskFixture;$t=Task;$fields=@($good|Where-Object {$_.FieldKey -ne 'unit_weight'})+@(@{FieldKey=$key;Value='120';Unit='kg';Scope=$(if($key -eq 'total_weight'){'total'}else{'unit'})}); Assert (Record $t.Task.id $fields).Ok; $r=Get-QuoteReadinessForConversationText -Text (BL 'Please verify this packing data.') -ConvoName 'Closure Buyer' -WithTaskEvidence; Assert $r.Ready } }
Case D06 { ClearTaskFixture;$t=Task; $bad=@(@{FieldKey='carton_count';Value='0';Unit='pieces';Scope='goods'},@{FieldKey='unit_weight';Value='-5';Unit='bananas';Scope='goods'},@{FieldKey='unit_dimensions';Value='50x40';Unit='cm';Scope='goods'},@{FieldKey='delivery_address';Value='unknown';Scope='destination'});$saved=Record $t.Task.id $bad;Assert $saved.Ok 'raw partial reply retained';Assert (@(Get-HumanTaskConfirmedFields @(Get-HumanTaskList -TaskId $t.Task.id)[0]).Count -eq 0) 'invalid fields unpublished'; $r=Get-QuoteReadinessForConversationText -Text (BL 'Please verify this packing data.') -ConvoName 'Closure Buyer' -WithTaskEvidence;Assert (-not $r.Ready) }
Case D07 {ClearTaskFixture;$t=Task;Assert (Record $t.Task.id @($good[1])).Ok;Assert (Record $t.Task.id @(@{FieldKey='unit_weight';Value='15';Unit='kg';Scope='unit'})).Ok;$r=Get-ConversationFacts -Conversation (ConvertTo-MessageList (BL 'Please verify this packing data.') 'Closure Buyer') -Buyer 'Closure Buyer' -WithTaskEvidence;Assert ($r.CargoFacts.ByKey.unit_weight.Status -eq 'conflict');Assert (-not (Set-HumanTaskStatus $t.Task.id resolved)) }
Case D08 { foreach($value in @('Amazon FTW1','123 Main Street, Hamburg 20095')){Assert (Test-CargoFieldValue delivery_address $value '' destination).Valid}; foreach($value in @('unknown','Amazon FAKE999','TBD')){Assert (-not (Test-CargoFieldValue delivery_address $value '' destination).Valid)} }
Case D09 { foreach($raw in @('{broken','','  ','{"version":2,"tasks":"wrong"}')){ ClearTaskFixture; $file=Get-HumanTaskFile; New-Item -ItemType Directory -Path (Split-Path $file -Parent) -Force|Out-Null; [IO.File]::WriteAllText($file,$raw); [IO.File]::WriteAllText(($file+'.bak'),'backup');$before=[IO.File]::ReadAllBytes($file);try{$n=Task;Assert (-not $n.StoreOk)}catch{};Assert ([Convert]::ToBase64String([IO.File]::ReadAllBytes($file)) -eq [Convert]::ToBase64String($before));Assert ([IO.File]::ReadAllText(($file+'.bak')) -eq 'backup') } }
Case D10 { ClearTaskFixture;$a=Task;Assert $a.StoreOk;Assert (Add-HumanTaskNotification $a.Task.id -Delivered $false);$b=New-OrUpdate-HumanTask -Buyer 'Second Buyer' -Kind human_requested -Status pending_human;Assert $b.StoreOk;Assert (@(Get-HumanTaskList).Count -eq 2);Assert ((Read-HumanTaskStore).Version -ge 2) }
Case D11 {ClearTaskFixture;$t=Task;[IO.File]::WriteAllText((Get-HumanTaskFile),'{broken');$threw=$false;try{$e=Get-ActionEvidenceForTask -Buyer 'Closure Buyer' -TaskId $t.Task.id}catch{$threw=$true};Assert $threw 'unreadable evidence cannot be healthy empty';$facts=Get-ConversationFacts (ConvertTo-MessageList (BL '10 cartons, total weight 100 kg.') 'Closure Buyer');Assert $facts.HasWeight }
Case D12 {ClearTaskFixture;$t=Task;$all=@(Get-HumanTaskList);Set-HumanTaskField $all[0] supplierKey '';Assert (Save-HumanTaskStore $all);$a=Get-ActionEvidenceForTask -Buyer 'Closure Buyer' -TaskId $t.Task.id -SupplierIdentity 'email:one@example.invalid';$b=Get-ActionEvidenceForTask -Buyer 'Closure Buyer' -TaskId $t.Task.id -SupplierIdentity 'email:two@example.invalid';Assert $a.ExactTaskMatch;Assert (-not $b.ExactTaskMatch) }
Case D12-full-email {foreach($value in @('factory+packing@sub.example.invalid','factory+packing@sub.other.invalid')){$candidate=@(Get-CargoContactCandidates ('Supplier email is '+$value+'.')|Where-Object Key -eq supplier_contact);Assert ($candidate.Count -eq 1 -and $candidate[0].Value -eq $value) 'whole mailbox retained';Assert ((Get-SupplierIdentity $candidate[0].Value).Key -eq ('email:'+$value))}}
Case D13 {ClearTaskFixture;$t=Task;$r=Add-HumanTaskActionRecord -Id $t.Task.id -ActionKind contacted -Source operator-entry -RecordedBy operator -SourceRef 'call:fixture' -AtUtc '2026-10-05T04:01:00Z' -RawContent 'Called supplier and discussed packing.';Assert $r.Ok;$e=Get-ActionEvidenceForTask -Buyer 'Closure Buyer' -TaskId $t.Task.id;Assert ($e.ContactedRecorded -and -not $e.SupplierReplyRecorded);Assert (Record $t.Task.id @()).Ok;$e=Get-ActionEvidenceForTask -Buyer 'Closure Buyer' -TaskId $t.Task.id;Assert $e.SupplierReplyRecorded }
Case D14 {ClearTaskFixture;$t=Task;$r=Add-HumanTaskActionRecord -Id $t.Task.id -ActionKind supplier_reply -RawContent 'Waiting for supplier reply.';Assert (-not $r.Ok);Assert (-not (Get-ActionEvidenceForTask -Buyer 'Closure Buyer' -TaskId $t.Task.id).SupplierReplyRecorded) }
Case D15 {ClearTaskFixture;$t=Task;Assert (Record $t.Task.id $good).Ok;$fields=@(Get-HumanTaskConfirmedFields @(Get-HumanTaskList -TaskId $t.Task.id)[0]);$ref=@($fields|Where-Object FieldKey -eq unit_weight)[0].FactRef;Assert (Record $t.Task.id @(@{FieldKey='total_weight';Value='150';Unit='kg';Scope='total'}) $ref).Ok;$after=@(Get-HumanTaskConfirmedFields @(Get-HumanTaskList -TaskId $t.Task.id)[0]);Assert ($after.Count -eq 4) 'only targeted old field invalidated';Assert (@($after|Where-Object FieldKey -eq unit_weight).Count -eq 0);Assert (@($after|Where-Object FieldKey -eq carton_count).Count -eq 1) }
Case D16 {ClearTaskFixture;$t=Task;Assert (-not (Set-HumanTaskStatus $t.Task.id resolved));$all=@(Get-HumanTaskList);Set-HumanTaskField $all[0] missingFields @();Assert (Save-HumanTaskStore $all);Assert (-not (Set-HumanTaskStatus $t.Task.id resolved)) 'immutable verification items survive dynamic empty';Assert (Record $t.Task.id $good).Ok;Assert (Set-HumanTaskStatus $t.Task.id resolved);$e=Get-ActionEvidenceForTask -Buyer 'Closure Buyer' -TaskId $t.Task.id;Assert ($e.ResolvedRecorded -and -not $e.IsOpen);Assert (@(Get-TaskConfirmedEvidence -Buyer 'Closure Buyer' -Conversation (ConvertTo-MessageList (BL 'Can you quote?' 1791172920000L) 'Closure Buyer')).Count -eq 4);ClearTaskFixture;$t=Task;Assert (Set-HumanTaskStatus $t.Task.id closed -Resolution 'cancelled');Assert (-not (Get-ActionEvidenceForTask -Buyer 'Closure Buyer' -TaskId $t.Task.id).ResolvedRecorded) }
Write-Output "RESULT closure_s1 pass=$script:pass fail=$script:fail root=$root"
if($script:fail){exit 1}
