# apply_suggestion.ps1 - Apply ONE accepted suggestion, with base-hash check, backup and rollback.
#
# [SPEC 5 2026-10-03] Guarantees enforced here:
#   1) Only a suggestion in the 'accepted' state can be applied. Being listed, existing on disk, or
#      having been generated by the scheduled task are NOT acceptance.
#   2) The target file must be byte-identical to what it was when the suggestion was generated
#      (baseHash). If it changed - a human edited it - the apply is REFUSED and the suggestion is
#      re-validated instead of overwriting the newer work.
#   3) The target file is backed up before any write.
#   4) After writing, the offline acceptance check runs. If it fails, the backup is restored and the
#      failure reason is kept on the record.
#   5) The "keep the newest N" truncation that the old optimizer used is GONE. Applying only ever
#      APPENDS, so no existing rule - least of all a hard constraint - can be dropped.
#
# Usage:
#   powershell -ExecutionPolicy Bypass -NoProfile -File apply_suggestion.ps1 -Id sug-1a2b3c4d5e6f7a8b
#   powershell -ExecutionPolicy Bypass -NoProfile -File apply_suggestion.ps1 -Id <id> -WhatIf
param(
    [Parameter(Mandatory = $true)][string]$Id,
    [switch]$WhatIf,
    [switch]$SkipValidation,
    [string]$LogDir = "",
    [string]$DataDir = "",
    [string]$ValidationScript = ""
)

$ErrorActionPreference = "Stop"
. (Join-Path $PSScriptRoot "config.ps1")
. (Join-Path $PSScriptRoot "lib\suggestions.ps1")
if (-not $LogDir) { $LogDir = Get-SkillPath "scripts" }
if (-not $DataDir) { $DataDir = Get-SkillPath "data" }
if (-not $ValidationScript) { $ValidationScript = Join-Path $PSScriptRoot "..\tools\acceptance\replay.ps1" }

$s = Get-SuggestionById -DataDir $DataDir -Id $Id
if (-not $s) { Write-Output ('APPLY-NOT-FOUND ' + $Id); exit 1 }
if ($s.status -ne 'accepted') {
    Write-Output ('APPLY-REFUSED ' + $Id + ': status is "' + $s.status + '", only an accepted suggestion may be applied.')
    Write-Output 'Accept it first with review_suggestions.ps1 -Accept <id>.'
    exit 2
}

$targetName = [string]$s.target.file
$targetPath = Join-Path $LogDir $targetName
if (-not (Test-Path $targetPath)) { Write-Output ('APPLY-ERR target file missing: ' + $targetPath); exit 1 }

$currentHash = Get-FileSha256 $targetPath
if ($s.baseHash -and $currentHash -ne $s.baseHash) {
    # A newer human edit wins. Refuse and ask for a fresh proposal instead of overwriting it.
    Set-SuggestionStatus -DataDir $DataDir -Id $Id -Status 'pending' -Note ('base file changed: was ' + $s.baseHash + ', now ' + $currentHash + ' - re-validate before applying') | Out-Null
    Write-Output ('APPLY-REFUSED-BASE-CHANGED ' + $Id)
    Write-Output ('  target:   ' + $targetPath)
    Write-Output ('  expected: ' + $s.baseHash)
    Write-Output ('  actual:   ' + $currentHash)
    Write-Output '  The file changed after this suggestion was generated. Nothing was written and no manual edit was overwritten.'
    Write-Output '  The suggestion is back to pending with the reason recorded; regenerate or re-validate it.'
    exit 3
}

$proposed = [string]$s.change.after
$pointer = [string]$s.target.pointer
Write-Output ('APPLY-PLAN ' + $Id)
Write-Output ('  file:     ' + $targetPath)
Write-Output ('  pointer:  ' + $pointer)
Write-Output ('  content:  ' + $proposed)
if ($WhatIf) { Write-Output 'APPLY-WHATIF: nothing written'; exit 0 }

$backupDir = Join-Path (Get-SuggestionDir $DataDir) 'backups'
if (-not (Test-Path $backupDir)) { New-Item -ItemType Directory -Path $backupDir -Force | Out-Null }
$stamp = Get-Date -Format 'yyyyMMdd_HHmmss'
$backupPath = Join-Path $backupDir ($targetName + '.' + $stamp + '.bak')
Copy-Item $targetPath $backupPath -Force
Write-Output ('APPLY-BACKUP ' + $backupPath)

function Restore-AndFail([string]$Reason) {
    Copy-Item $backupPath $targetPath -Force
    Set-SuggestionStatus -DataDir $DataDir -Id $Id -Status 'apply-failed' -Note $Reason | Out-Null
    Write-Output ('APPLY-FAILED-ROLLED-BACK ' + $Id + ': ' + $Reason)
    Write-Output ('  restored from ' + $backupPath)
    exit 4
}

# ---- write ----
try {
    if ($pointer -eq 'reply_rules.never') {
        $rules = Get-Content $targetPath -Raw -Encoding UTF8 | ConvertFrom-Json
        $cur = @()
        if ($rules.reply_rules.never) { $cur = @($rules.reply_rules.never) }
        # Append-only. No truncation, so a hard constraint can never be squeezed out.
        foreach ($c in $cur) { if (([string]$c).Trim().ToLowerInvariant() -eq $proposed.Trim().ToLowerInvariant()) { Restore-AndFail 'duplicate rule already present' } }
        $rules.reply_rules.never = @($cur + $proposed)
        [System.IO.File]::WriteAllText($targetPath, ($rules | ConvertTo-Json -Depth 12), (New-Object System.Text.UTF8Encoding($true)))
        Write-Output ('APPLY-WROTE reply_rules.never += 1 (total ' + @($rules.reply_rules.never).Count + ')')
    } elseif ($targetName -like '*reply_scenarios.md') {
        $existing = Get-Content $targetPath -Raw -Encoding UTF8
        if ($existing.Contains($proposed)) { Restore-AndFail 'duplicate example already present' }
        $block = [string][char]10 + [string][char]10 + '## reviewed-addition' + [string][char]10 + [string][char]10 + $proposed + [string][char]10
        [System.IO.File]::AppendAllText($targetPath, $block, (New-Object System.Text.UTF8Encoding($false)))
        Write-Output 'APPLY-WROTE reply_scenarios.md += 1 section'
    } else {
        Restore-AndFail ('unsupported target pointer: ' + $pointer)
    }
} catch {
    Restore-AndFail ('write error: ' + $_.Exception.Message)
}

# ---- validate ----
if ($SkipValidation) {
    Write-Output 'APPLY-VALIDATION-SKIPPED (explicitly requested)'
} else {
    $ok = $true
    $detail = 'no validation script found'
    if (Test-Path $ValidationScript) {
        try {
            $out = @(& powershell -ExecutionPolicy Bypass -NoProfile -File $ValidationScript 2>&1)
            $detail = ($out | Select-Object -Last 5) -join ' | '
            if ($LASTEXITCODE -ne 0) { $ok = $false }
        } catch { $ok = $false; $detail = 'validation threw: ' + $_.Exception.Message }
    } else {
        # Fall back to a structural check so an apply is never left unverified.
        try {
            $r = Get-Content (Join-Path $LogDir 'reply_rules.json') -Raw -Encoding UTF8 | ConvertFrom-Json
            $n = @($r.reply_rules.never).Count
            $ok = ($n -gt 0)
            $detail = ('structural check: reply_rules.json parses, never rules = ' + $n)
        } catch { $ok = $false; $detail = 'structural check failed: ' + $_.Exception.Message }
    }
    if (-not $ok) {
        $reason = 'offline validation failed: ' + $detail
        Set-SuggestionStatus -DataDir $DataDir -Id $Id -Status 'apply-failed' -Note $reason | Out-Null
        Copy-Item $backupPath $targetPath -Force
        Write-Output ('APPLY-FAILED-ROLLED-BACK ' + $Id + ': ' + $reason)
        Write-Output ('  restored from ' + $backupPath)
        exit 4
    }
    Write-Output ('APPLY-VALIDATED ' + $detail)
}

Set-SuggestionStatus -DataDir $DataDir -Id $Id -Status 'applied' -Note ('applied, backup at ' + $backupPath) | Out-Null
Write-Output ('APPLY-OK ' + $Id)
Write-Output ('  backup: ' + $backupPath)
Write-Output '  To undo: copy the backup over the target file. No other file was touched.'
